### ISSUE TITLE
[help wanted] 请教下前辈对SimGCL理解

### ISSUE THREAD

**Issue by oceanlvr** [Coder-Yu/SELFRec#11]
冒昧打扰前辈，不好意思。
SimGCL上的工作很有启发性，但是我有点疑问。文章提出关键不是droupout增强，而是均匀的分布达到去偏的效果
但题目起的是《Are Graph Augmentations Necessary? Simple Graph
Contrastive Learning for Recommendation》让我觉得有一些迷惑，dourpout base的增广在 GBRSs 上是不太好的，其他非 droupout 增广方法在 GBRs 上是否有必要？

**Comment by Coder-Yu** [comment]
你可以看下我的综述https://arxiv.org/abs/2203.15876 里面总结了不同的data augmentation的类型，基于结构的扰动只是一种，还有其他种类。

**Comment by oceanlvr** [comment]
谢谢前辈百忙之中的回复，谢谢 :)
