### ISSUE TITLE
SSL4Rec在yelp上的结果不太好

### ISSUE THREAD

**Issue by 255-1** [Coder-Yu/SELFRec#15]
大佬您的SimGCL的文章实验里面DNN+SSL应该对应的就是SSL4Rec这个模型吧, 但是这个模型我在yelp数据集上跑结果如下
> *Best Performance* 
Epoch: 22, Hit Ratio:0.0183126791239777 | Precision:0.009372236958443855 | Recall:0.02152239714180159 | MDCG:0.01612651549405071

但是我看您的两篇论文SimGCL和XSimGCL中的结果比这个好很多recall达到0.0483, 不知道是不是我哪里设置得有问题, 我就改了conf文件中的数据位置为yelp

**Comment by Coder-Yu** [comment]
这个模型很难调，也没有开源代码，给作者发邮件也不回。我自己实现的跑出来结果较差，需要反复调参。0.0483我没跑出来，参考了一下SGL论文里面的结果。后面有空我再调调。

**Comment by Coder-Yu** [comment]
你多调一下ssm loss和NCE loss里面的温度参数

**Comment by 255-1** [comment]
多谢解答, 我去试试, 如果效果好了我回来说

**Comment by Coder-Yu** [comment]
根据经验，基于dnn的模型只用interaction效果一般都不好，像NCF实际上效果是不如单纯的MF的
