### ISSUE TITLE
[Questions] negative items are not token as input of batch_softmax loss 

### ISSUE THREAD

**Issue by Zhanghahah** [Coder-Yu/SELFRec#17]
Hey Yu. Your work is so impressful. Thanks for your open source contribution. I also have some problems when  using this project. From the figure below you can see, as the implementation of SSL,  key point of this work is to construct negative samples by masking or dropout tech. I noticed that you constructed negative samples from item list which are not interacted with user in-batch. But the '_neg' are not the input of loss calculation. Could you please explain this and  help solve my questions？ thanks a lot!
![image](https://user-images.githubusercontent.com/44437422/206906106-b73c6141-8f8c-4c0e-a8db-b7a3e77c5f78.png)

**Comment by Coder-Yu** [comment]
In-batch negative sampling is used. So, it is unnecessary to explicitly feed negatives to batch_softmax loss.
