### ISSUE TITLE
[Bug]The program generate recommendation list containing duplicate element

### ISSUE THREAD

**Issue by byhbyhyoyo** [Coder-Yu/SELFRec#18]
When I was debugging, I found recommendation list  containing duplicate element.
At base/graph_recommender.py, 87 line, rec_list = self.test().
I got a rec_list whose content is {'22': [('1190', 0.00026), ('325', 0.00023), ('325', 0.00023), ('166', 0.00017), ('166', 0.00017)],....}
'325' and '166' appear twice.

I checked your code. I found  bug at util/algorithm.py,  152 line , program is` for iid, score in enumerate(candidates)`
Your candidates[:K] has been assigned to n_candidates, but 152 line still traverse all candidate and failure to avoid repetition.

When I changed util/algorithm.py 152 line to `for iid, score in enumerate(candidates[K:]):` and 153 line is `iid = iid + K`. 
Bug was fixed.

**Comment by Coder-Yu** [comment]
Thank you very much for identifying this small bug. My bad.

Just now I ran the code with the corrected version, the performance has a slight improvement (about 0.0005 on Yelp 2018). It seems the bug did not impact too much.

**Comment by byhbyhyoyo** [comment]
Thank you very much for your attention and correction of this problem.

**Comment by byhbyhyoyo** [comment]
Thank you very much for your attention and correction of this bug.
