### ISSUE TITLE
Origin of the datasets

### ISSUE THREAD

**Issue by melfm** [Coder-Yu/SELFRec#20]
Hello,

I was wondering where I can find the original dataset you are using here? I understand the accompanied dataset has already been preprocessed (btw exactly how its been pre-processed is unclear to me). Is there a resource access to the raw dataset? 

For instance I was expecting the amazon-book dataset to be something similar to [this](https://www.kaggle.com/code/die9origephit/amazon-data-science-books-plotly-visualization) where you can visualize the data as done in this example. It's unclear to me whether there is one standard dataset being used (as I see multiple papers in this survey referencing) or whether there are different variations.

Thanks!

**Comment by melfm** [comment]
Furthermore, I'm not able to train the sequential models such as `SASRec` and `CL4SRec` with other datasets such as `amazon-beauty`. I see this one has a different format compared to amazon-kindle and yelp2018. Could you advice on the difference between these data processing? And how you ran all the models on yelp2018 to reproduce the SOTs?

**Comment by Coder-Yu** [comment]
link of amazon-book: https://www.dropbox.com/sh/20l0xdjuw0b3lo8/AABBZbRg9hHiN42EHqBSvLpta?dl=0

I got this dataset from https://github.com/huangtinglin/NGCF-PyTorch/tree/master/Data

format of datasets for sequential models: 
user item

**Comment by melfm** [comment]
Hello - Thank you for your response.
But the dataset don't seem to be the same format  for amazon-book dataset. For instance for test.txt what are these columns?
```
4 0 1
7 0 1
9 0 1
17 2 1
19 2 1
21 3 1
29 4 1
31 4 1
```

And for the Yelp2018, how do you process the data into the user: interacted items format? Because only amazon-beauty has the correct form to be trained with a sequential model.

**Comment by Coder-Yu** [comment]
1 means interacted. You can regard it as a placeholder.

Yelp2018 is processed for graph recommenders, not for sequential models.
