### ISSUE TITLE
代码性能问题

### ISSUE THREAD

**Issue by LDY911** [Coder-Yu/SELFRec#23]
求问大佬，使用SELFRec好像GPU利用率并不高，需要设置什么参数可以提高运行速度

**Comment by Coder-Yu** [comment]
你觉得哪里不够快？

**Comment by LDY911** [comment]
> 你觉得哪里不够快？就是我在自己电脑上跑SEPT和在GPU服务器上跑速度一样

**Comment by LDY911** [comment]
> > 你觉得哪里不够快？就是我在自己电脑上跑SEPT和在GPU服务器上跑速度一样

自己电脑用的CPU跑的

**Comment by Coder-Yu** [comment]
那可能是你的pytorch版本装成了cpu版

**Comment by Coder-Yu** [comment]
用的cpu排的，排序代码是调用numba加速过后的。排序因为是全排所有item，即使调用gpu的排序也不会像矩阵运算那么块的
