### ISSUE TITLE
关于模型测试的疑问

### ISSUE THREAD

**Issue by 404creep** [Coder-Yu/SELFRec#24]
你好我是一名RS小白，在复现XSimGCL中发现测试时总会出错，后来发现一些数据集中的测试集用户是没有在训练集出现过的，没有学到对应的user_embeding。 可惜我没在你的代码看到处理相关情况的部分，请问您是如何处理这种情况的呢？

**Comment by Coder-Yu** [comment]
排序肯定是比训练的batch慢的。我这里12700k的cpu测试一次yelp018大概6-7s，也还是挺快的
