### ISSUE TITLE
后续还会更新别的模型吗

### ISSUE THREAD

**Issue by 404creep** [Coder-Yu/SELFRec#25]
我看ssl_sequential_models 的选择中有DuoRec，请问后面会更新这个模型的实现代码吗，我看该模型的issue中很多人都说达不到论文中的效果，但作者都没有回应

**Comment by Coder-Yu** [comment]
我实现出来的版本 确实相比SASRec提升不怎么明显。后续还会更新一些序列模型，可能要等一阵
