### ISSUE TITLE
想请问下训练集样本处理问题

### ISSUE THREAD

**Issue by downeykking** [Coder-Yu/SELFRec#26]
您好！我发现SELFRec中的data在处理训练集样本时：

假设训练数据内容是用户0与项目0、1、2交互，用户1与项目0、1交互，即总共有5条交互数据在训练集中。对于训练集的构造，SELFRec是使用了`(0，0，_)，(0，1，_)，(0，2，_)，(1，0，_)，(1，1，_)`
三元组的3个元素分别代表用户ID、正样本ID、负样本ID，下划线代表随机抽取的负样本。并且保证了训练集内不重不漏地包含了所有的交互数据。请问我的理解正确吗？

但是在LightGCN和SGL中，我发现它们使用的方法都是先采样训练集样本数个用户，然后再得到正负样本，请问这两种方法的哪种更为合理呢？如果要把LightGCN作为对比实验，是不是需要定义类似它一样的采样方法呢？以及如果我想设计我自己的推荐算法，您建议我应该使用哪种采样方式呢？

非常感谢！

**Comment by Coder-Yu** [comment]
采样方法应该保证每个样本能得到均等的被抽取几率。不管程序如何，如果样本曝光几率一样，都可以。
作为baseline的方法应该保证基础设置如采样方法相同，得到的结果会更公平。

**Comment by downeykking** [comment]
> 采样方法应该保证每个样本能得到均等的被抽取几率。不管程序如何，如果样本曝光几率一样，都可以。 作为baseline的方法应该保证基础设置如采样方法相同，得到的结果会更公平。

好的 谢谢！
