### ISSUE TITLE
请教关于模型的测试过程

### ISSUE THREAD

**Issue by wisdomGEsLA** [Coder-Yu/SELFRec#28]
大佬你好，我是RS这块的菜鸟，我发现按照默认设置运行的话好像没有使用到验证集，验证集是必要的吗？

**Comment by Coder-Yu** [comment]
是必要的，但你把验证集当测试集用就可以了。先在验证集上根据结果找到好的超参数，再用最佳的超参数去测试集上评估模型

**Comment by Coder-Yu** [comment]
用测试集的时候，直接在配置文件中test.set那里填上测试集的位置

**Comment by zzoxi** [comment]
尊敬的作者，您好，我也有类似的问题还不太明白。 (1)默认源代码中traning.set与test.set均填写了对应的位置。我阅读源代码是每轮epoch使用fast_evaluation中调用测试集test_set进行评估，如何实现文章中训练集-验证集-测试集7：1：2呢？ (2)运行模型最后的Testing...结果和某一轮训练的Best Perfomance结果为什么总是一致。模型的最终测试结果是取最好的一轮结果吗？  谢谢作者

**Comment by Coder-Yu** [comment]
手动划分，把7:1:2里面的1（验证集）先作为测试集输入，选好超参后再替换成测试集的路径。
模型的最终测试结果是取最好的一轮结果。

**Comment by zzoxi** [comment]
> 模型的最终测试结果是取最好的一轮结果
谢谢作者。这种取结果方法常用吗？比如我使用此代码框架设置轮数40轮，在30轮取得最佳结果，后面训练导致结果下降，取第30轮的best performance填写到实验表格中？之前我对深度学习理解的是选定epoch参数，训练结束后进行测试？谢谢作者耐心的回复

**Comment by Coder-Yu** [comment]
取最好的一轮结果就行。

**Comment by lsc332211** [comment]
> 手动划分，把7:1:2里面的1（验证集）先作为测试集输入，选好超参后再替换成测试集的路径。 模型的最终测试结果是取最好的一轮结果。

大佬你好，请问这种结果的取得方式是否不太严谨，我看源代码直接8：2分为训练：测试，每轮epoch结束后面向测试集调参...还是说如果对比实验中所有模型都才用最好的epoch结果进行对比也行？

**Comment by Coder-Yu** [comment]
> 手动划分，把7:1:2里面的1（验证集）先作为测试集输入，选好超参后再替换成测试集的路径。 模型的最终测试结果是取最好的一轮结果。
这个可以

> 我看源代码直接8：2分为训练：测试，每轮epoch结束后面向测试集调参...
这个不可以

你说的可能是那个movielens的dataset划分吧 那个数据集我的论文里没用过

**Comment by lsc332211** [comment]
> > 手动划分，把7:1:2里面的1（验证集）先作为测试集输入，选好超参后再替换成测试集的路径。 模型的最终测试结果是取最好的一轮结果。
> > 这个可以
> 
> > 我看源代码直接8：2分为训练：测试，每轮epoch结束后面向测试集调参...
> > 这个不可以
> 
> 你说的可能是那个movielens的dataset划分吧 那个数据集我的论文里没用过

不是 代码里所有的数据集都是只有train和test吧..

**Comment by Coder-Yu** [comment]
这些数据集大多数是直接从NGCF LightGCN的原repo拿过来的 他们发布出来就是这个样子 并不是我划分的。这些论文属于常规baseline了，为了跟他们比较，只能用他们的划分。自己再额外划分一下training set做验证。上传的数据集是他们原来的。

**Comment by lsc332211** [comment]
> 这些数据集大多数是直接从NGCF LightGCN的原repo拿过来的 他们发布出来就是这个样子 并不是我划分的。这些论文属于常规baseline了，为了跟他们比较，只能用他们的划分。自己再额外划分一下training set做验证。上传的数据集是他们原来的。你去SGL LightGCN NGCF几个原始repo看一下就知道了。

好的好的 谢谢大佬
