### ISSUE TITLE
SASRec vs CL4SRec

### ISSUE THREAD

**Issue by LiLiParty** [Coder-Yu/SELFRec#30]
Thank you very much for your great work.

I compared the accuracy of the two models (SASRec and CL4SRec in your code) in Amazon-beauty, and SASRec was superior.
Empirically, contrastive learning based on InfoNCE should work better, pushing the representation space of sequential embeddings too.

Could you tell me what do you think of this? Is this due to defferences in datasets and lack of hyperparameter tuning (or the all-ranking protocol)?

**Comment by Coder-Yu** [comment]
Tuning hyperparameters can lead to slightly better results, but the improvement is still not that impressive. The first author refused to release the code of CL4SRec. So be cautious to the results claimed in the paper of CL4SRec.

**Comment by LiLiParty** [comment]
Thank you for your time!
