### ISSUE TITLE
关于SimGCL去除图增强部分表现

### ISSUE THREAD

**Issue by 404creep** [Coder-Yu/SELFRec#32]
Excellent job！SimGCL是GCL4Rec近年来最有启发的工作，论文中说SGL中的图增强是不必要的部分，不做任何图增强的SGL-WA应该表现也不差，可我在SimGCL去除噪声模块后进行对比学习表现却非常差
*Best Performance* 
Epoch: 2, Hit Ratio:0.00173  |  Precision:0.00088  |  Recall:0.00203  |  NDCG:0.00165
请问这是因为什么问题呢

**Comment by Coder-Yu** [comment]
图增强确实是不是必须的，但augmentation还是要有的。你这个情况应该是loss没有降下去的缘故。我在个别数据集上有遇到这个情况，如果你是用的selfrec的代码，你调小（大）一下正则项的系数应该可以帮助降低loss。去除噪声之后的结果，我在simgcl的论文实验部分也有报告结果，你可以看下参数敏感性分析那里。

**Comment by Coder-Yu** [comment]
另外SimGCL在最终聚合的时候去掉了第0层的embedding 你试试加上应该是可以优化的

**Comment by 404creep** [comment]
关于去除噪声之后的结果，我看论文参数敏感性分析那里噪声为0时在yelp2018上比最好的结果只差了一点
我用的时selfrec代码，参数和数据集都是默认的，确实我观察到rec_loss和cl_loss没怎么下降，cl_lambda我没有仔细调，只调小（大）reg.lambda（从0.1~1e-9）结果仍然很差,loss还是降不下去，reg_loss倒是上升了
*Best Performance* 
Epoch: 1, Hit Ratio:0.01029  |  Precision:0.00526  |  Recall:0.01191  |  NDCG:0.01018
请问可以公布一下噪声为0时SimGCL的超参数设置吗，这个似乎挺难调的

**Comment by Coder-Yu** [comment]
我试了下 你调大最大迭代次数 如果是yelp2018的默认参数的话 把eps设为0之后 大概需要50-60次达到最佳效果。前面30多次迭代loss下降很缓慢

**Comment by 404creep** [comment]
好的，谢谢
