### ISSUE TITLE
关于SimGCL测试的一点疑问

### ISSUE THREAD

**Issue by LarFii** [Coder-Yu/SELFRec#37]
作者您好，想请问一下在SimGCL对于训练集中未出现却在测试集中出现的User会怎样处理呢。我在进行测试的时候，发现实际测试的user数量略小于给定的测试集中的user数。例如该数据集测试集中有1w名user，但实际给出的推荐结果只有9740名user。
<img width="1309" alt="image" src="https://github.com/Coder-Yu/SELFRec/assets/49157727/145b85f9-0a18-410c-9cf2-f649d5f842f1">

**Comment by LarFii** [comment]
例如user58就未被推荐
<img width="1286" alt="image" src="https://github.com/Coder-Yu/SELFRec/assets/49157727/e89c83ed-aff6-421d-b885-57bf728e0efc">

**Comment by Coder-Yu** [comment]
hi，因为有的用户interaction太少，可能出现训练集里有，测试集没有的情况。对于只在其中一个出现的情况，就不进行预测。就你举的例子，用户58如果只在训练集里出现，对他的预测没法评估，就直接剔除掉。反之，如果只在测试集出现，则他没有训练好的embedding，无法进行预测。另外这个数据集的划分是公开的，并不是我自己进行的划分。

**Comment by LarFii** [comment]
您发给我的信件已收到，谢谢。

**Comment by LarFii** [comment]
> hi，因为有的用户interaction太少，可能出现训练集里有，测试集没有的情况。对于只在其中一个出现的情况，就不进行预测。就你举的例子，用户58如果只在训练集里出现，对他的预测没法评估，就直接剔除掉。反之，如果只在测试集出现，则他没有训练好的embedding，无法进行预测。另外这个数据集的划分是公开的，并不是我自己进行的划分。

除了单独出现的情况，58这个user在训练集和测试集中均有出现，但同样未被预测。
<img width="885" alt="image" src="https://github.com/Coder-Yu/SELFRec/assets/49157727/d1fbd68c-5e5d-456e-8781-ecd73f45cff8">

**Comment by LarFii** [comment]
测试用的数据集发到您的邮箱中了

**Comment by LarFii** [comment]
明白了，58交互的那个item在训练集中未出现。谢谢作者解答。

**Comment by Coder-Yu** [comment]
另外一个可能性是，该用户在测试集里互动过的item没有出现在训练集，这样也无法对其进行预测评估。完全基于interaction的推荐模型都是transductive的，对于训练集未见过的用户和商品，无法对其推荐和评估。你check一下，应该是这种情况

**Comment by LarFii** [comment]
但是其他模型，例如baseline中的SGL，他综合考虑了训练集验证集测试集中的user和item，那这样在评测的时候，simgcl和SGl实际评测的交互会存在差异吧。像这种只在一边出现的user和item，SGL同样会进行预测。
<img width="695" alt="image" src="https://github.com/Coder-Yu/SELFRec/assets/49157727/9bba5e12-55a7-4ce2-867d-a363578c96ba">

**Comment by Coder-Yu** [comment]
我的论文里面baseline和自己的方法都是使用自己的框架实验的，所以这里是不存在差异的，不会影响结果可信性。你用SELFRec跑一下SGL跟原始论文结果对比一下就知道是差不多的。至于你说的那种只在一边出现的项目和用户，尽管可以预测，但因为其对应embedding无法被训练，预测结果也是无效的。

**Comment by LarFii** [comment]
明白了，谢谢作者
