### ISSUE TITLE
设置了相同的种子，加对比学习后每次运行结果不同。

### ISSUE THREAD

**Issue by 767166590** [Coder-Yu/SELFRec#38]
![1](https://github.com/Coder-Yu/SELFRec/assets/46867069/719d20f5-9027-4872-af0a-edaf9a61a5c6)
![image](https://github.com/Coder-Yu/SELFRec/assets/46867069/c462b715-23cc-4c97-9de5-4997e6e7e7e7)
两次对比学习损失函数误差逐渐增加

**Comment by Coder-Yu** [comment]
每一次epoch会对训练数据shuffle，不一样很正常

**Comment by 767166590** [comment]
但我运行SGL，MHCN等模型，每次运行的结果是一模一样，是可以复现的。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Junliang Yu ***@***.***&gt;
发送时间: 2023年6月21日 02:51
收件人: Coder-Yu/SELFRec ***@***.***&gt;
抄送: 767166590 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Coder-Yu/SELFRec] 设置了相同的种子，加对比学习后每次运行结果不同。 (Issue #38)





 
每一次epoch会对训练数据shuffle，不一样很正常

**Comment by Coder-Yu** [comment]
为啥在意这个？不能复现结果？

**Comment by 767166590** [comment]
对，我自己的代码不能复现（每次的误差会有百分之1-3）。但是去掉对比学习是可以复现的，对比学习用的是INFONCE（您的版本和ｒｅｃｂｏｌｅ的都尝试了）

**Comment by Coder-Yu** [comment]
这个就不清楚了，毕竟不是自己的代码
