### ISSUE TITLE
Request for settings of the Amazon-Electronics dataset

### ISSUE THREAD

**Issue by QwQ2000** [Coder-Yu/SELFRec#39]
I am impressed by your work XSimGCL on self-supervised learning for GNN-based recommender systems. I have read your paper and code, and I would like to reproduce your results on the Amazon-Electronics dataset. However, I could not find the pre-processed version of this dataset or the detailed pre-processing pipeline. Could you please kindly share the pre-process settings of the Amazon-Electronics dataset, such as the train/test split file and the k-core setting? I would greatly appreciate your help. Thank you for your time and attention.

**Comment by Coder-Yu** [comment]
Hi
I got this dataset from https://cseweb.ucsd.edu/~jmcauley/datasets/amazon/links.html.
I might just removed the ratings smaller than 4 and keep the rest.

You can download the version used in my paper here (https://www.dropbox.com/sh/xtnkdz1kwu82oi1/AACE0I3MXIKc2Zs8-WZERdVra?dl=0).

**Comment by QwQ2000** [comment]
Thank you for your prompt reply :-)
