### ISSUE TITLE
Is there any Repo for updated version

### ISSUE THREAD

**Issue by smbilal1984** [Coder-Yu/SELFRec#4]
I am facing error for  'tensorflow' has no attribute 'contrib' while executing the algo MHCN, 

is there any repo to support advanced version of tansorflow . 

AttributeError                            Traceback (most recent call last)
Input In [2], in <cell line: 4>()
     29     exit(-1)
     30 rec = SELFRec(conf)
---> 31 rec.execute()
     32 e = time.time()
     33 print("Running time: %f s" % (e - s))

File C:\SELFRec-main/SELFRec-main\SELFRec.py:28, in SELFRec.execute(self)
     26 exec(import_str)
     27 recommender = self.config['model.name'] + '(self.config,self.training_data,self.test_data,**self.kwargs)'
---> 28 eval(recommender).execute()

File C:\SELFRec-main/SELFRec-main\base\recommender.py:71, in Recommender.execute(self)
     69 self.print_model_info()
     70 print('Initializing and building model...')
---> 71 self.build()
     72 print('Training Model...')
     73 self.train()

File C:\SELFRec-main/SELFRec-main\model\graph\MHCN.py:62, in MHCN.build(self)
     60 self.weights = {}
     61 self.n_channel = 4
---> 62 initializer = tf.contrib.layers.xavier_initializer()
     63 self.user_embeddings = tf.Variable(initializer([self.data.user_num, self.emb_size]))
     64 self.item_embeddings = tf.Variable(initializer([self.data.item_num, self.emb_size]))

AttributeError: module 'tensorflow' has no attribute 'contrib'

**Comment by Coder-Yu** [comment]
SELFRec using tensorflow 1.14+. Another repo named Recbole-gnn implements MHCN as well, and it is purely based on pytorch. You can try that one if needed.
