### ISSUE TITLE
请教关于SimGCL的训练问题

### ISSUE THREAD

**Issue by ByeKira** [Coder-Yu/SELFRec#42]
您好，感谢大佬提供一个简洁高效的框架。在训练SimGCL的过程中我发现似乎随着cl_rate的增大，模型在训练初期需要更多的epoch来实现在验证集上的推荐效果的增长，您认为如果对SimGCL采用early stop策略，阈值设置为多少比较稳妥？

**Comment by Coder-Yu** [comment]
cl_rate调大的话，初期会loss会下降的很慢，early stop可能导致underfitting，不推荐。你可以试试XSimGCL，比SimGCL训练快很多。

**Comment by ByeKira** [comment]
> cl_rate调大的话，初期会loss会下降的很慢，early stop可能导致underfitting，不推荐。你可以试试XSimGCL，比SimGCL训练快很多。

好的，我试试，XSimGCL也不推荐使用early stop吗？

**Comment by Coder-Yu** [comment]
你可以试试，不过XSimGCL收敛会快一些，训练也很稳定，感觉也没必要。
