### ISSUE TITLE
Seeking advice on data cleaning and optimizing for fast execution.

### ISSUE THREAD

**Issue by HeyWeCome** [Coder-Yu/SELFRec#43]
Dear Yu, 

Thank you very much for your outstanding work. I have been attempting to build a recommendation system framework from scratch recently, but I encountered some issues. I attempted to find answers within SELFRec, but I'm still a bit confused. Therefore, I would like to ask you about two questions, hoping to receive your guidance: 

Firstly, I notice that you have already prepared preprocessing for large sparse datasets like Yelp. I want to know your cleaning rules. Currently, I've only done some basic processing:
```python
# Filter out users with less than 5 occurrences
user_counts = data_df['user_id'].value_counts()
data_df = data_df[data_df['user_id'].isin(user_counts[user_counts >= 5].index)]

# Create a mapping of unique user and item IDs to sequential integers
user_id_map = {id: i for i, idx in enumerate(data_df['user_id'].unique())}
item_id_map = {id: i for i, idx in enumerate(data_df['item_id'].unique())}
data_df['user_id'] = data_df['user_id'].map(user_id_map)
data_df['item_id'] = data_df['item_id'].map(item_id_map)

# Filter out interactions with a rating less than 3
data_df = data_df.loc[data_df['rating'] >= 3].copy()  # Make a copy of the filtered DataFrame
data_df.drop(columns=['rating'], inplace=True)
```

Secondly, I want to know the strategies you use when conducting quick evaluation. When I use a full ranking for evaluation, the code runs relatively slowly.

Thank you for your valuable work again. I've been reading your article on self-supervised learning recently, and it's been absolutely fascinating.

**Comment by Coder-Yu** [comment]
Q1. I did not do data cleaning because I just downloaded well-prepared datasets processed by others.
Q2. Use some third-party library like numba or just invoke the topk function in pytorch to speed up your evaluation.

**Comment by HeyWeCome** [comment]
Roger, thanks for the reply, I'll try again.

**Comment by ZeshenTian** [comment]
> Dear Yu,
> 
> Thank you very much for your outstanding work. I have been attempting to build a recommendation system framework from scratch recently, but I encountered some issues. I attempted to find answers within SELFRec, but I'm still a bit confused. Therefore, I would like to ask you about two questions, hoping to receive your guidance:
> 
> Firstly, I notice that you have already prepared preprocessing for large sparse datasets like Yelp. I want to know your cleaning rules. Currently, I've only done some basic processing:
> 
> ```python
> # Filter out users with less than 5 occurrences
> user_counts = data_df['user_id'].value_counts()
> data_df = data_df[data_df['user_id'].isin(user_counts[user_counts >= 5].index)]
> 
> # Create a mapping of unique user and item IDs to sequential integers
> user_id_map = {id: i for i, idx in enumerate(data_df['user_id'].unique())}
> item_id_map = {id: i for i, idx in enumerate(data_df['item_id'].unique())}
> data_df['user_id'] = data_df['user_id'].map(user_id_map)
> data_df['item_id'] = data_df['item_id'].map(item_id_map)
> 
> # Filter out interactions with a rating less than 3
> data_df = data_df.loc[data_df['rating'] >= 3].copy()  # Make a copy of the filtered DataFrame
> data_df.drop(columns=['rating'], inplace=True)
> ```
> 
> Secondly, I want to know the strategies you use when conducting quick evaluation. When I use a full ranking for evaluation, the code runs relatively slowly.
> 
> Thank you for your valuable work again. I've been reading your article on self-supervised learning recently, and it's been absolutely fascinating.

I also encountered the second issue you mentioned. I solved it by adding `@jit(nopython=True)` decorator to the `find_k_largest()` function, just like the author did.
