### ISSUE TITLE
一些关于xsimgcl模型训练的问题

### ISSUE THREAD

**Issue by T0L0ve** [Coder-Yu/SELFRec#44]
当我通过训练出一个模型后，如果我有了新的数据该如何在原有模型的基础上继续训练（新的数据可能包含之前数据集中未出现过的物品和用户）？我看到模型初始化会根据输入的数据构建一个scr矩阵，我是要在原有csr矩阵的基础上补上新数据的部分然后训练，还是仅对新的数据训练后给旧的embedding加上新增数据的embedding。

**Comment by Coder-Yu** [comment]
最好的效果当然是重头训练 增量训练可能效果没那么好
