### ISSUE TITLE
LightGCN Recall@20 复现问题

### ISSUE THREAD

**Issue by oceanlvr** [Coder-Yu/SELFRec#46]
尊敬的作者您好～在使用您的代码复现论文的时候包括SGL NCL SimGCL XSimGCL 指标都是对应的。都没有问题～

但是在 LIghtGCN 上很差距leaderboard的效果还差很多。没有改动您的代码和超参数，也多次实验。没办法达到大部分论文中的leaderboard和论文中的指标（yelp2018）。可能是我漏掉了什么步骤吗～

<img width="207" alt="image" src="https://github.com/Coder-Yu/SELFRec/assets/36698124/97742a00-37cb-4768-ab2e-4931aac81980">
<img width="543" alt="image" src="https://github.com/Coder-Yu/SELFRec/assets/36698124/ea543348-fa8d-4948-82d8-99dff7f978f7">

<img width="372" alt="image" src="https://github.com/Coder-Yu/SELFRec/assets/36698124/a78ba334-9b92-4cd5-a7f2-b1e9663a4e15">

**Comment by Coder-Yu** [comment]
LightGCN要用较小的学习率才能大体复现出来 比如0.0002。这里我参考了SGL的结果。用0.001我也复现不出来。

**Comment by oceanlvr** [comment]
谢谢前辈的回复，是的我看其他论文也是这个指标，我再试试～

**Comment by oceanlvr** [comment]
感谢您出色的工作

**Comment by ChanglongZheng** [comment]
> 谢谢前辈的回复，是的我看其他论文也是这个指标，我再试试～

hello~我在跑LightGCN的时候也是遇到这样的问题，也没能到达论文中的指标，和论文中可能有3、4%的差距，请问一下你解决了嘛

**Comment by oceanlvr** [comment]
@ChanglongZheng 是的，使用非常低的学习率可以接近这个指标。很多对比论文中 LightGCN 这类无对比学习的方法可能是单独调整成最好的参数偏多，而不是和对比学习方法使用一样的 learning rate
