### ISSUE TITLE
About Amazon Book settings

### ISSUE THREAD

**Issue by danielemalitesta** [Coder-Yu/SELFRec#51]
Dear authors,

Thanks a lot for sharing the code and datasets for your model. Would you kindly share the settings you used to obtain the results for SimGCL on Amazon Book? That would be useful for my research.

Thank you again.

Best regards,
Daniele

**Comment by Coder-Yu** [comment]
Please refer to the hyperparameter sensitivity analysis section in my paper, where the optimal parameter settings have been presented.

**Comment by danielemalitesta** [comment]
Thank you very much for your fast reply!
