### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by akajinchen** [Coder-Yu/SELFRec#52]
你好，感谢你的开源框架和开源数据集。但是我注意到，在Xsimgcl这篇文章中，有一个Amazon-Electronics数据集我没有在这里找到，请问下这个数据集可以开源吗？

望回复，万分感谢。

**Comment by Coder-Yu** [comment]
参见 https://github.com/Coder-Yu/SELFRec/issues/39

**Comment by akajinchen** [comment]
感谢你的回复
