### ISSUE TITLE
你好，我想问doubanbook数据集的验证集是怎么生成的，从interaction.txt划分出来的么， 

### ISSUE THREAD

**Issue by ttttthy** [Coder-Yu/SELFRec#57]

**Comment by Coder-Yu** [comment]
是的。

**Comment by ttttthy** [comment]
那可以问下是什么比例么，验证集好像也没有第三列评分数据，
我划分训练验证测试集8:1:1后，验证集的数据很少，训练的效果也很不好


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Coder-Yu/SELFRec"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月26日(星期五) 下午2:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Coder-Yu/SELFRec] 你好，我想问doubanbook数据集的验证集是怎么生成的，从interaction.txt划分出来的么，  (Issue #57)





 
是的。

**Comment by ttttthy** [comment]
> 7：1：2 训练集 验证集 测试集 论文结果是合并了训练集和验证集之后再训练得到的

好的谢谢
