### ISSUE TITLE
关于douban-book数据集的疑问

### ISSUE THREAD

**Issue by byhbyhyoyo** [Coder-Yu/SELFRec#58]
作者您好，很感谢您提供了开源的框架供我们研读学习。
其中有个问题想要咨询下您，即dataset文件夹下的douban-book数据集中，有interaction.txt, train.txt，test.txt 以及 trust.txt
其中train.txt和test.txt的数量加起来等于interation.txt中的记录数量，并且trust.txt的记录在interation.txt中似乎未出现。
所以想问下，trust.txt是干什么用的哈？

**Comment by Coder-Yu** [comment]
trust.txt是社交关系 interaction.txt里面是user和item的交互数据
