### ISSUE TITLE
关于数据集 Amazon-Electronics 及论文中图3的请教

### ISSUE THREAD

**Issue by Yangzhi22** [Coder-Yu/SELFRec#60]
作者及团队成员，您们好：
 
非常荣幸能够学习到您们团队这么出色的研究成果，
请问能分享一下Amazon-Electronics 数据集以及图3的绘制代码以供更好地理解和学习您们的工作吗？

如果您们能分享的话，麻烦您发送至邮箱：572208009@qq.com

希望能进一步学习您们的研究成果。

祝：工作顺利，事事如意！

**Comment by Coder-Yu** [comment]
https://github.com/Coder-Yu/SELFRec/issues/59

https://github.com/Coder-Yu/SELFRec/issues/39
