### ISSUE TITLE
关于DiffNet++复现

### ISSUE THREAD

**Issue by umsimonchen** [Coder-Yu/SELFRec#64]
尊敬的余教授：

感谢早前几次细心的解答。不好意思又有问题要请教一下您。
请问Selfrec有机会推出torch版的DiffNet++吗？很奇怪，纵观所有开源平台，貌似除了原作者并没有人复现DiffNet++，复现DiffNet也是少之又少。
此外，客观的说，原作者的代码貌似存在冗余，例如没有使用循坏很好地解决传播问题。而且对DiffNet的复现，大家写的代码也和源代码有出入。请问您对此有什么看法。

期待您的答复。

**Comment by Coder-Yu** [comment]
不好意思 我不关注social recommendation很久了。DiffNet我之前是按原论文描述的技术细节实现的 因为方法比较简单，没有参考源代码。在不使用预训练的feature的情况下 效果比较一般。DiffNet++我直接用的源代码跑的，印象不太深刻了，应该是存在你说的部分问题的。

**Comment by umsimonchen** [comment]
好的。感谢您的解答。
