### ISSUE TITLE
关于模型调优的问题

### ISSUE THREAD

**Issue by akajinchen** [Coder-Yu/SELFRec#65]
感谢余老师出色的工作和开源的代码，最近我在使用SELFRec去跑对比实验，发现对模型进行网格调参不是非常的方便，不知道老师之前有没有用过这个框架去进行模型调优，有没有什么好的方法推荐，望回复，感谢老师。

**Comment by Coder-Yu** [comment]
写一个shell脚本就可以了。直接python脚本也可以，调用一下os.system(cmd)。嵌套多个循环用以grid search

**Comment by akajinchen** [comment]
> 写一个shell脚本就可以了。直接python脚本也可以，调用一下os.system(cmd)。嵌套多个循环用以grid search

感谢老师回复，确实这样很高效。但是我实现的时候发现SELFRec中的参数是在conf文件中，每次需要写入一个新的conf文件，不是特别的方便，不知道老师有没有好的方法指导

**Comment by Coder-Yu** [comment]
现有的设计似乎不能直接通过不重写conf的方法来传递参数。你可以考虑自己改一下。

重写conf的话，我这里有一段我直接写的代码，也不是很麻烦。

def modifyConfig(file,key,value):
    with open(file) as f:
        content = f.readlines()

        for i,item in enumerate(content):
            if item.split('=')[0]==key:
                content[i] = item.split('=')[0]+'='+value+'\n'
    with open(file,'w') as f:
        for item in content:
            f.write(item)

**Comment by akajinchen** [comment]
感谢

**Comment by Coder-Yu** [comment]
你可以利用输入重定向到文件，避免中间手动输入方法名，这样运行一次脚本就可以调完一个方法了。
