### ISSUE TITLE
您好，SELFRec为什么最新更新的代码及论文都不是和社交推荐相关了，您是认为社交推荐可扩展性很少了是吗

### ISSUE THREAD

**Issue by TerkyTerky** [Coder-Yu/SELFRec#69]

**Comment by Coder-Yu** [comment]
这个库是以自监督推荐算法为主题的，社交推荐只覆盖了自监督相关的几个。你可以考虑用大模型做社交推荐

**Comment by TerkyTerky** [comment]
我想冒昧地问一下，这个大模型目前来说偏向于利用文本做推荐，太过于泛化了，我应该怎么针对每一个数据集去做相应的prompt；还有就是利用大模型做社交推荐应该怎么处理社交网络关系，我最近看的一些文章兵没有提及相关的处理

**Comment by Coder-Yu** [comment]
多读最新的文献吧 都能找到详细的答案

**Comment by akajinchen** [comment]
> 多读最新的文献吧 都能找到详细的答案
余老师最近也是在做大模型和图推荐结合的方向吗？

**Comment by Coder-Yu** [comment]
> 余老师最近也是在做大模型和图推荐结合的方向吗？

分开做的 主要是指导博士做
