### ISSUE TITLE
数据集中的rating是否有作用

### ISSUE THREAD

**Issue by 255-1** [Coder-Yu/SELFRec#7]
大佬你好, 我是个RS小白, 最近看了BUIR的代码使用的yelp数据集, 个人理解最后预测的就是用户会不会和物品交互, 并不会预测rating的数值. 不知道是不是这样理解, 数据集的txt第三列是个数字就行?
因为我看ui_graph.py 中的training_set_u 这个变量虽然记录了rating, 但是在graph_recommender.py下的test() 函数里面的并没有用变量li的内容. 
其次我想问一下, ui_graph.py中的__create_sparse_bipartite_adjacency()函数中rating是不是也和数据集中rating没有关系, 因为是用np.ones_like()生成的, 只是代表是否相连的关系?

**Comment by Coder-Yu** [comment]
不考虑连接权重的话， 分数没影响。这个库里的算法都是item recommendation，没有以rating prediction为输出的。十几 二十年前的算法主要是预测评分的，现在的主要预测项目被推荐的几率。

**Comment by Coder-Yu** [comment]
BTW, 感兴趣可以关注下我们新的模型XSimGCL，比SimGCL更快更强。

**Comment by 255-1** [comment]
多谢大佬解答，一定会关注的！

**Comment by Coder-Yu** [comment]
不是大佬😂，交流学习
