### ISSUE TITLE
NCL的e-step问题

### ISSUE THREAD

**Issue by umsimonchen** [Coder-Yu/SELFRec#73]
十分感谢您对推荐系统贡献。

针对NCL复现代码中的e-step，请问代码中选择在前20epoch进行e-step是empirical的吗？请问调整e-step对性能会有怎么的变化吗？

期待您的答复。

**Comment by Coder-Yu** [comment]
应该是empirical的 建议你去recbole下面提问 这个工作是他们提出的，这里的代码主要是基于他们的源码实现的。他们应该更清楚细节。

**Comment by umsimonchen** [comment]
好的 十分感谢
