### ISSUE TITLE
作者您好，我想使用知识图谱和XSimGCL结合来达到性能提升可行吗

### ISSUE THREAD

**Issue by JayWu5** [Coder-Yu/SELFRec#74]
作者您好，我想使用知识图谱和XSimGCL结合来达到性能提升可行吗，这是我做自己硕士论文的一个想法，初步结合发现性能指标还略微降低了一下不知道哪里有问题。

**Comment by Coder-Yu** [comment]
应该是可以的，这个得需要你自己去探究了。

**Comment by JayWu5** [comment]
我初步实践发现性能反而下降了一点点，以为是我设想是错误的，想请教一下您有没有什么建议。
&nbsp;


吴杰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Junliang ***@***.***&gt;; 
发送时间: 2024年10月15日(星期二) 下午4:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Coder-Yu/SELFRec] 作者您好，我想使用知识图谱和XSimGCL结合来达到性能提升可行吗 (Issue #74)














 
应该是可以的，这个得需要你自己去探究了。
