### ISSUE TITLE
关于数据集Amazon-kindle

### ISSUE THREAD

**Issue by umsimonchen** [Coder-Yu/SELFRec#75]
尊敬的余教授：

您好。

请问在Dataset文件夹中的Amazon-kindle数据集有来源吗？

刚开始以为是Amazon-book，后来对比一下用户数等发现不太一样。在Amazon官网也貌似没有类似大小的数据集。

还是说这是经过预处理去除低分评价的某个数据集呢？

期待您的回答。

**Comment by Coder-Yu** [comment]
之前从UCSD的Julian McAuley的数据集网站上下载的，他们后来调整了网站，似乎找不到这个数据集了。我下载下来后去除了评分低于4的，此外没什么改动

**Comment by umsimonchen** [comment]
十分感谢您的解答
