### ISSUE TITLE
SimGCL中的Regulating Uniformity实现问题请教

### ISSUE THREAD

**Issue by 255-1** [Coder-Yu/SELFRec#8]
大佬我想请教一下SimGCL中公式(9)的实现, 我看论文是两个特征相减求得L2范数, 但是loss里面的l2_reg_loss()实现是单纯的范数求和, 我个人理解公式是一种类似pair-wise的相对的特征一致, 但是代码里面实现的loss就是希望范数小, 不知道大佬是怎么考虑的

**Comment by Coder-Yu** [comment]
公式9并没有用到模型训练里面，只是实验证明了SimGCL可以通过噪声的模长调节均匀性，公式9只是一个metric用来计算均匀性的

**Comment by 255-1** [comment]
哦哦, 那l2_reg_loss()这个函数就是希望embedding的各个项的值小一点吗

**Comment by Coder-Yu** [comment]
是这样的

**Comment by 255-1** [comment]
多谢解答!
